server:
  port: 7600

spring:
  application:
    name: nacos-consumer-feign-depart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        # 默认为public
#        namespace: my_hsf_id
#        # 默认为DEFAULT_GROUP
#        group: my_hsf_group
#        # 默认为DEFAULT
#        cluster-name: myhsfCluster





