server:
  port: 7100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka


spring:
  application:
    name: eureka-provider-7100

logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.abc.provider: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"

  # 开启shutdown监控终端
  endpoint:
    shutdown:
      enabled: true


